pipeline:
  Step1:
    image:  markhobson/maven-chrome
    group: g1
    shm_size: 1024000000
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      DISPLAY: ":99.0"
    commands:
      - mvn clean test 
