pipeline:
  Step1:
    image:  markhobson/maven-chrome
    shm_size: 1024000000
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      DISPLAY: ":99.0"
    commands:
      - mvn clean test 

  Step2:
    image: markhobson/maven-chrome
    shm_size: 1024000000
    commands:
      - mvn clean

  Step3:
    image: markhobson/maven-chrome
    shm_size: 1024000000
    commands:
      - mvn clean test site
