pipeline:
  build:
    image:  maven:3.5-alpine
    commands:
      - mvn clean test site 

services:
  selenium:
    image: selenium/hub

  chrome:
    image: selenium/node-chrome
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: "4444"
